version: '3'
services:
    mlflow-server:
        image: mlflow-server:latest
        ports:
            - "5000:5000"
        volumes:
            - /data/mlflow:/mlflow
    experiments:
        image: experiments:latest
        environment:
            - MLFLOW_TRACKING_URI=http://mlflow-server:5000
            - PYTHONUNBUFFERED=0
        volumes:
            - /data/mlflow:/mlflow
            - /data/data-sets:/data/data-sets