# Generated by Django 2.2 on 2020-03-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat', '0002_auto_20200314_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag_results',
            name='hashtag_search_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hashtag_search',
            name='results_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hashtag_results',
            name='bot_heatmap',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
