# Generated by Django 3.0.4 on 2020-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat', '0003_auto_20200315_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag_results',
            name='hashtag_search_id',
        ),
        migrations.RemoveField(
            model_name='hashtag_search',
            name='results_id',
        ),
        migrations.AlterField(
            model_name='hashtag_results',
            name='bot_heatmap',
            field=models.CharField(max_length=200),
        ),
    ]
