# Generated by Django 3.0.4 on 2020-04-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat', '0004_auto_20200401_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag_results',
            name='ml_output',
            field=models.CharField(max_length=500),
        ),
    ]
