# Generated by Django 3.0.4 on 2020-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat', '0005_auto_20200401_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag_search',
            name='user_hashtag',
            field=models.CharField(default='foo', max_length=100),
        ),
    ]
