# Generated by Django 3.0.4 on 2020-04-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat', '0006_auto_20200401_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag_search',
            name='bot_heatmap',
            field=models.CharField(default='moo', max_length=100),
        ),
        migrations.AddField(
            model_name='hashtag_search',
            name='ml_output',
            field=models.CharField(default='moo', max_length=100),
        ),
    ]
