# Generated by Django 3.0.4 on 2020-04-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tat', '0007_auto_20200401_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag_search',
            name='bot_heatmap',
        ),
        migrations.RemoveField(
            model_name='hashtag_search',
            name='ml_output',
        ),
    ]
